name: Test VapourSynth Setup Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        vapoursynth-version: [69, 70, 71, 72]
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run local Set up VapourSynth action
        uses: ./
        with:
          vapoursynth-version: ${{ matrix.vapoursynth-version }}
          python-version: ${{ matrix.python-version }}

      - name: Verify VapourSynth installation
        shell: python
        run: |
          import vapoursynth
          print(vapoursynth.core)
